Code to process dev PR

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -38,22 +38,45 @@ jobs:
           cd scripts && ../ve1/bin/pip3 install -r requirements.txt && cd ..
           cd scripts && ../ve1/bin/python3 setup.py install && cd ..
 
-      - name: Show values
-        run: |
-          echo "sender: ${{ github.event.sender.login }}"
-          echo "user: ${{ github.event.pull_request.user.login }}"
-          echo "branch: ${{ github.event.pull_request.head.ref }}
-          echo "pr title: ${{ github.event.pull_request.title }}
-          echo "pr body: ${{ github.event.pull_request.body }}"
-
-      - name: Check if only release file in PR
-        id: check_version_in_PR
+      - name: Check if only release file in PR and if user is authorized
+        id: check_only_version_in_PR_and_authorized
         working-directory: ./pr-branch
         run: |
-          # check if release file only is included in PR
-          ve1/bin/release-checker --api-url=${{ github.event.pull_request._links.self.href }}
+          # check if release file only is included in PR and if so that user is authorized.
+          ve1/bin/release-checker --api-url=${{ github.event.pull_request._links.self.href }} \
+                                  --sender=${{ github.event.sender.login }}
+
+      - name: Check if PR created as part of release process
+        id: check_created_release_pr
+        if: ${{ steps.check_version_in_PR.outputs.PR_includes_release_only != 'true' }}
+        run: |
+          # check if PR was created as part of release processing
+          ve1/bin/release-checker --api-url=${{ github.event.pull_request._links.self.href }} \
+                                  --sender=${{ github.event.sender.login }} \
+                                  --pr_branch=${{ github.event.pull_request.head.ref }} \
+                                  --pr_title=${{ github.event.pull_request.title }}
+
+      - name: Reflect on PR Content
+        id: reflect_on_pr_content
+        run: |
+          # Determine if and how processing should continue
+          if [ "${{ steps.check_created_release_pr.outputs.dev_release_branch }}" = "true" ]; then
+             echo "PR created by release processing"
+             echo "::set-output name=merge::true"
+             echo "::set-output name=release::true"
+          elif [ "${{ steps.check_only_version_in_PR_and_authorized.outputs.dev_release_branch }}" = "true" ]; then
+             echo "PR contains only release_info file"
+             echo ":set-output name=create_pull_requests::true"
+          elif [ "${{ steps.check_only_version_in_PR_and_authorized.outputs.sender_not_authorized }}" = "true" ]; then
+             echo "Unauthorized Request"
+             exit 1
+          else
+             echo "No release work to do"
+             exit
+          fi
 
       - name: Checkout charts repo
+        if: ${{ steps.reflect_on_pr_content.outputs.create_pull_requests == "true" }}
         uses: actions/checkout@v2
         with:
           repository: ${{ env.REPOSITORY_ORGANIZATION }}/charts
@@ -61,6 +84,7 @@ jobs:
           path: "charts-repo"
 
       - name: Checkout development repo
+        if: ${{ steps.reflect_on_pr_content.outputs.create_pull_requests == "true" }}
         uses: actions/checkout@v2
         with:
           repository: ${{ env.REPOSITORY_ORGANIZATION }}/development
@@ -68,12 +92,13 @@ jobs:
           path: "dev-repo"
 
       - name: Set up Python 3.x Part 1
+        if: ${{ steps.reflect_on_pr_content.outputs.create_pull_requests == "true" }}
         uses: actions/setup-python@v2
         with:
           python-version: "3.9"
 
       - name: Set up Python scripts on main branch
-        if: ${{ steps.check_version_in_PR.outputs.PR_includes_release == 'true' }}
+        if: ${{ steps.reflect_on_pr_content.outputs.create_pull_requests == "true" }}
         run: |
           # set up python scripts
           echo "set up python script in $PWD"
@@ -81,23 +106,16 @@ jobs:
           cd scripts && ../ve1/bin/pip3 install -r requirements.txt && cd ..
           cd scripts && ../ve1/bin/python3 setup.py install && cd ..
 
-      - name: Check for restricted files and user permissiom
-        id: check_authorization
-        if: ${{ steps.check_version_in_PR.outputs.PR_includes_release == 'true' }}
-        run: |
-          # check for a restricted file and, if found, check user has permissiom
-          ve1/bin/check-user --api-url=${{ github.event.pull_request._links.self.href }} --user=${{ github.event.pull_request.user.login }}
-
       - name: Check if version updated
         id: check_version_updated
-        if: ${{ steps.check_version_in_PR.outputs.PR_includes_release == 'true' }}
+        if: ${{ steps.reflect_on_pr_content.outputs.create_pull_requests == "true" }}
         run: |
           # check if version file was changed
           ve1/bin/release-checker --version=${{ steps.check_version_in_PR.outputs.PR_version }}
 
       - name: Sync the repositories
         id: sync_repositories
-        if: ${{ steps.check_version_in_PR.outputs.PR_includes_release == 'true' }}
+        if: ${{ steps.check_version_updated.outputs.release_updated == 'true' }}
         env:
           BOT_NAME: ${{ secrets.BOT_NAME }}
           BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
@@ -106,5 +124,49 @@ jobs:
           # sync the repositories
           ve1/bin/releaser --version=${{ steps.check_version_in_PR.outputs.PR_version }} --pr_dir="./pr-branch" --development_dir="./dev-repo" --charts_dir="./charts-repo"
 
+      - name: reflect on release creation progress
+        id: relflect_progress
+        if: ${{ steps.check_version_updated.outputs.release_updated == 'true' }}
+        run: |
+          # determine what should be done next
+          if [ "${{ steps.sync_repositories.charts_pr_error }}" = "true" ] || [ "${{ steps.sync_repositories.dev_pr_error }}" = "true" ]; then
+              echo "Errors creating pull requests"
+              exit 1
+          if [ "${{ steps.sync_repositories.charts_pr_created }}" = "true" ] || [ "${{ steps.sync_repositories.charts_pr_created }}" = "true" ]; then
+              echo "At least one PR was created - we have a release"
+              echo "::set-output name=merge::true"
+          if [ "${{ steps.sync_repositories.dev_pr_not_needed }}" = "true" ]; then
+              echo "No charts so create release"
+              echo "::set-output name=release::true"
+          fi
 
+      - name: Approve PR
+        id: approve_pr
+        if: ${{ steps.relflect_progress.outputs.merge == 'true'}} ||  ${{ steps.reflect_on_pr_content.outputs.merge == 'true'}}
+        uses: hmarr/auto-approve-action@v2
+        with:
+          github-token:  ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Merge PR
+        id: merge_pr
+        if: ${{ steps.relflect_progress.outputs.merge == 'true'}} ||  ${{ steps.reflect_on_pr_content.outputs.merge == 'true'}}
+        uses: pascalgn/automerge-action@v0.13.1
+        env:
+          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
+          MERGE_METHOD: squash
+          MERGE_LABELS: ""
+
+      - name: Check for PR merge
+        if: ${{ steps.relflect_progress.outputs.merge == 'true'}} ||  ${{ steps.reflect_on_pr_content.outputs.merge == 'true'}}
+        run: |
+          ve1/bin/check-auto-merge --api-url=${{ github.event.pull_request._links.self.href }}
+
+      - name: Create the the release
+        id: create_release
+        if: ${{ steps.relflect_progress.outputs.release == 'true'}} ||  ${{ steps.reflect_on_pr_content.outputs.release == 'true'}}
+        uses: softprops/action-gh-release@v1
+        with:
+          tag_name: ${{ steps.check_version_in_PR.outputs.PR_version }}
+          body: ${{ steps.check_version_in_PR.outputs.PR_release_body }}
+        env:
+          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
